local typedefs = require 'kong.db.schema.typedefs'

return {
  cluster_stats_heartbeat = {
    name = 'cluster_stats_heartbeat', ---the actual table in the database
    primary_key = {'node_id'},
    db_export = false,
    generate_admin_api = false,
    fields = {
      {node_id = {type = 'string'}}, -- node id generated by kong
      {created_at = typedefs.auto_timestamp_s}, -- timestamp at which this node was bootstrapped
      {updated_at = typedefs.auto_timestamp_s} -- timestamp of last heartbeat
    }
  }
}
